# This rule is not used by the project sdk-directory itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to webapp.localhost resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sdk-directory
    app.kubernetes.io/managed-by: kustomize
  name: todo-viewer-role
rules:
- apiGroups:
  - webapp.localhost
  resources:
  - todoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.localhost
  resources:
  - todoes/status
  verbs:
  - get
