apiVersion: webapp.example.com/v1
kind: Hello
metadata:
  labels:
    app.kubernetes.io/name: helloworld-operator
    app.kubernetes.io/managed-by: kustomize
  name: hello-sample
spec:
  # TODO(user): Add fields here
